### ISSUE TITLE
Primo BO fix for UnPaywall suppression issue

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#52]
Third Iron code conflicting with Unpaywall for Primo.
Third Iron has released the fix that was suppressing the Unpaywall links in the brief display. Add the following line to your custom.js file:
enableLinkOptimizer: false,

**Comment by jechols** [comment]
I don't know where that setting would go - I need more context for this. I don't know what "Unpaywall" is, and as far as I can tell none of our code is doing anything with such a system/service/customization.

Can you point me to where you saw that information? The "line" of JS you added there is just a setting that would need to be passed into a function or an object of some kind.

**Comment by MargaretA-UO** [comment]
https://thirdiron.atlassian.net/wiki/spaces/BrowZineAPIDocs/pages/79200260/Ex+Libris+Primo+Integration

**Comment by MargaretA-UO** [comment]
That's the official documentation.  I took the info I originally put in the ticket from an email:
An update on this item for users who subscribe to Third Iron's Libkey and have turned on Links to PDFs in Unpaywall in their Primo Back Office.   

Third Iron has released the fix that was suppressing the Unpaywall links in the brief display. Add the following line to your custom.js file:
enableLinkOptimizer: false,
Unpaywall links that we had labelled "Free PDF" have returned to our brief display, above the Libkey links. 

![image](https://user-images.githubusercontent.com/76136640/159320642-acac6996-9494-445d-b95e-05f9e8793026.png)

**Comment by MargaretA-UO** [comment]
The item above is also in our catalog, so should be a good test case for us, as well. 
https://alliance-primo.hosted.exlibrisgroup.com/permalink/f/qgisft/TN_cdi_plos_journals_2544866499

**Comment by jechols** [comment]
I've been toying with various ways to make the browzine code do its thing, but nothing seems to change the output to include any unpaywall links. With or without that `enableLinkOptimizer` setting, nothing changes; mixing it in with the HathiTrust customization makes no difference; using what Corey had originally done to put these links in a separate location, same deal, nothing changes.

I can make all browzine links go away by removing the customization entirely, and I can alter the text in the links that do display, so I know the customization is in place and working for the pieces we've already been using (things like "Download PDF" or "View Journal Contents". But for whatever reason there is simply never anything "unpaywall" related that I can see.

I'm hoping this means there's a setting somewhere on your end that you haven't found, because otherwise I think we will have to just close this issue as not-fixable.

**Comment by MargaretA-UO** [comment]
Interesting.  And this is in BO or in VE?
Let me think about that.  I’ll let you know if I figure something out.
Thanks.
Margaret

**Comment by jechols** [comment]
Putting this on hold unless you have more info. This will have to be closed without a fix eventually, though, as I haven't heard back and (though I forgot to update you) I never found anything further in my own investigations.

**Comment by MargaretA-UO** [comment]
Let's go ahead and close this. Thanks.
