### ISSUE TITLE
VE - Show MMSIDs as in Primo

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#56]
This is a tool that is used frequently in Primo but is not yet available OTB in VE.

[Show MMS IDs](https://github.com/alliance-pcsg/ve-customizations/blob/main/show-mmsids.js )
This customization will display Institution Zone and Network Zone MMS IDs, if available, at the end of the metadata list in a full display record. In addition to inserting the code in and institution's custom.js file and adding showMmsid to var app=angular.module..., implementers should add custom values to the showMmsidOptions section:

/* Custom options for labels, and institution-specific trailing 4-digits for IZ MMS ID  */
app.constant('showMmsidOptions', {
  "izLabel": "MMS ID (IZ)", /* Field value for Institution Zone MMS ID */
  "nzLabel": "MMS ID (NZ)", /* Field value for Network Zone MMS ID */
  "izSuffix": "xxxx" /*institution-specific trailing 4 digits*/
});
Please see [this document](https://docs.google.com/spreadsheets/d/1Wyab3UPyUm34Ak9NQHg1sZWwkTNeqWCJ/edit?usp=sharing&ouid=115321540829379572112&rtpof=true&sd=true) to get your institution's 4-digit 'izSuffix' for editing the izSuffix value above.

Implementers may want to consider hiding the current MMS ID field in Alma, under View Configuration > Edit Full Display Details.

**Comment by MargaretA-UO** [comment]
IZ Suffix for UO:  1852

**Comment by jechols** [comment]
This is implemented: https://alliance-uoregon.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma99127772501852&context=L&vid=01ALLIANCE_UO:UO&lang=en&search_scope=Everything&adaptor=Local%20Search%20Engine&tab=Rollup&query=any,contains,cat%20in%20the%20hat&offset=0

I'm not entirely sure how best to test it out other than browsing random things and seeing how they look compared to Primo, but even that is iffy since Primo shows a lot more metadata....

**Comment by MargaretA-UO** [comment]
And...apparently they (Alliance NRSG) are still tinkering with the code.  I think it's fine to leave what we have for now, and revisit in July.

**Comment by jechols** [comment]
Okay, I'll close this for now, then. File another ticket if/when we need further fixes.
